#!/bin/python3
# -*- coding: utf-8 -*-
# py_exec="$( dirname "${BASH_SOURCE[0]}" )/main.py"
# python3 "$py_exec" $@
import re
import sys
from contest_builder.main import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

