#!/bin/python3
# -*- coding: utf-8 -*-
# py_exec="$( dirname "${BASH_SOURCE[0]}" )/main.py"
# python3 "$py_exec" $@
import sys
from src.contest_builder.cli import app

if __name__ == "__main__":
    sys.exit(app())
