#!/bin/python3
# -*- coding: utf-8 -*-
# py_exec="$( dirname "${BASH_SOURCE[0]}" )/main.py"
# python3 "$py_exec" $@
import sys
from contest_builder.__main__ import main
if __name__ == '__main__':
    sys.exit(main())

