name: CI Pipeline

on:
  push:
    branches-ignore:
      - 'gh-pages'
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run tests
        run: pytest
